### ISSUE TITLE
Encoding problem on Windows

### ISSUE THREAD

**Issue by anetschka** [radomirbosak/duden#112] opened 2020-07-28 09:40 UTC
Hi,
I am trying to use the module on Windows 10. There seems to be an encoding issue here: 

![image](https://user-images.githubusercontent.com/17731067/88648051-e5756700-d0c6-11ea-9d29-69a34a854a17.png)

In other cases, the call terminates, but retrieves None:

![image](https://user-images.githubusercontent.com/17731067/88648216-105fbb00-d0c7-11ea-8cd3-ef0fa182b501.png)

Is there a quick fix or does it require further analysis? I'd also be ready to contribute!

**Comment by anetschka** [comment] 2020-07-28 09:48
I checked and confirm that it works on my Linux subsystem.

**Comment by radomirbosak** [comment] 2020-07-28 11:50
Hi @anetschka . Thanks for creating this issue. Unfortunately I don't have a windows 10 machine, so I cannot reproduce this bug right now. I also don't know about any quick fixes.

**Comment by anetschka** [comment] 2020-07-28 11:53
Hi @radomirbosak, are any Linux-only modules in the package?

**Comment by radomirbosak** [comment] 2020-07-28 11:54
Not that I know of.

**Comment by radomirbosak** [comment] 2020-07-28 11:56
Right now, I suspect the error might have something to do with how the `gzip` module handles utf-8 encoded characters.

**Comment by radomirbosak** [comment] 2020-07-28 11:59
If the bug is limited to the `gzip` module, a quickfix might be as simple as removing the caching decorators from the `request_word` and `request_search` functions.

```python
# @cached_response(prefix='')
def request_word(word):
    """
    Request word page from duden
    """
    url = URL_FORM.format(word=word)
    try:
        response = requests.get(url)
    except requests.exceptions.ConnectionError:
        raise Exception(_("Connection could not be established. "
                          "Check your internet connection."))

    if response.status_code == 404:
        return None
    response.raise_for_status()

    return response.text

...

# @cached_response(prefix='search-')
def request_search(word):
    """
    Request search page from duden
    """
    url = SEARCH_URL_FORM.format(word=word)
    return requests.get(url).text
```

This will cause repeated word-searching to slow down considerably because caching is turned off, but it may solve your issue.

**Comment by anetschka** [comment] 2020-07-28 12:03
I tried setting cache=False in line 119. This removes the error, but then nothing is found.

**Comment by radomirbosak** [comment] 2020-07-28 12:09
There is actually a `--no-cache` argument, so editing source may not be needed needed.
```bash
$ python3 run_duden.py --no-cache Glück
Glück, das
==========
Word type: Substantiv, Neutrum
Separation: Glück
Meaning overview:
 0. etwas, was Ergebnis des Zusammentreffens besonders günstiger Umstände ist; besonders günstiger Zufall, günstige Fügung des Schicksals

 1. das personifiziert gedachte Glück (1); Fortuna

 2.  a. angenehme und freudige Gemütsverfassung, in der man sich befindet, wenn man in den Besitz oder Genuss von etwas kommt, was man sich gewünscht hat; Zustand der inneren Befriedigung und Hochstimmung
     b. einzelne glückliche Situation; glückliches Ereignis, Erlebnis

Synonyms:
 0. Glücksfall, Glückssache, Glücksstern

Typical compounds:
 - Adjektive: groß, unverschämt, vollkommen, persönlich, wahr, privat, pur, rein
 - Verben: gehaben, küssen, versuchen, hasten, suchen, wünschen, bringen, fassen
 - Substantive: Erfolg, Zufriedenheit, Freude, Unglück, Pech, Zufall, Wohlstand
```

**Comment by radomirbosak** [comment] 2020-07-28 12:09
Interesting. I'm not sure why the word is not found.

**Comment by anetschka** [comment] 2020-07-28 12:15
> Interesting. I'm not sure why the word is not found.

This might well be because of caching: It didn't find the word due to the error, then this result seems to be cached. Other searches replicate the error. You might be right in that the gzip module causes the error when the program tries to write a word to the cache file (I always use codec for handling utf-8 encodings). Ideally, the module should work both on Windows and Linux. Any ideas on how the caching mechanism could be refactored?

**Comment by anetschka** [comment] 2020-07-28 12:22
@radomirbosak Could you somehow verify whether this fixes the problem (eplicitly setting the encoding to utf8). I will push it to my fork of the repo (got a result now!):

def decorator_itself(func):
        def function_wrapper(cache_key, cache=True, **kwargs):
            cachedir = Path(xdg_cache_home) / 'duden'
            filename = prefix + sanitize_word(cache_key) + '.gz'
            full_path = str(cachedir / filename)

            if cache:
                # try to read from cache
                cachedir.mkdir(exist_ok=True)
                try:
                    with gzip.open(full_path, 'rt', encoding='utf8') as f:
                        return f.read()
                except FileNotFoundError:
                    pass

            result = func(cache_key, **kwargs)

            if cache and result is not None:
                with gzip.open(full_path, 'wt', encoding='utf8') as f:
                    f.write(result)

            return result

        return function_wrapper
    return decorator_itself

**Comment by radomirbosak** [comment] 2020-07-28 13:30
If the problem lies with caching, for testing it might be necessary to clear the cache. On linux I do this with the 
```bash
rm ~/.cache/duden/*
```
command. I'm not sure what the location is in windows though.

**Comment by radomirbosak** [comment] 2020-07-28 13:33
The `encoding="utf-8"` change looks good. I saw it in some stackoverflow answers when I was googling the error you originally posted. However, I still don't know how to test whether it helps. Did it help you? I can help with creating the test case/environment if needed.

Maybe tomorrow I can try to test it in a windows docker container and hopefully, I'll be able to reproduce the bug.

**Comment by radomirbosak** [comment] 2020-07-28 13:36
Oh, I just noticed the pull request. Let me test that.

**Comment by anetschka** [comment] 2020-07-28 13:38
> Did it help you? 

Yes, I can run `python run_duden.py <word>` now, retrieving a result.

**Comment by radomirbosak** [comment] 2020-07-28 13:42
Great!  I just merged the pull request. Thank you for contributing. :)

**Comment by radomirbosak** [comment] 2020-07-28 13:42
@anetschka by the way, what do you use the `duden` module for, if I may ask?

**Closed by radomirbosak** 2020-07-28 13:42 UTC

**Comment by anetschka** [comment] 2020-07-28 13:46
@radomirbosak I am trying to improve spelling correction for German. Will you let me know when you update the Python module?

**Comment by radomirbosak** [comment] 2020-07-28 21:23
For the update reminder - I can do that, but in case I forget, easier for you might be to add the repository to your watching list, or directly subscribe to the releases RSS feed 
https://github.com/radomirbosak/duden/releases.atom

Spelling correction sounds interesting. Is there any particular feature you need and are missing from the `duden` module? As you can see from the issues tab, there's a lot of features that could be added, but unfortunately I don't so much time to work on them.

**Comment by anetschka** [comment] 2020-07-29 11:17
Hi @radomirbosak, for grammar and spell checking it would be very useful to harvest case information for prepositions, for instance. In German (like in Slovak, I guess), prepositions require the following noun to be in a specific grammatical case. Duden provides this information (e.g. https://www.duden.de/rechtschreibung/auf_Praeposition). I am not sure whether this is already implemented, because I have not yet used duden via python import, just through the CLI, and there was no grammar information. I am ready to look into this myself, but could you verify whether this type of information is parsed or not?

**Comment by radomirbosak** [comment] 2020-07-29 20:49
@anetschka , currently this information is not parsed.

By the way, for the preposition cases, do you need just the list of cases that the preposition connects with?

is it (Grammatik section)
```
Grammatik Info

Präposition mit Dativ und Akkusativ
```

or more specific binding information from the "Bedeutung" section?
```
c) zur Angabe des Übergangs, des Nacheinanders, der Aufeinanderfolge

Grammatik: zeitlich; mit Akkusativ 
```
(I see that not all meanings have grammar information)

The `duden` module supports currently just verb conjugation and noun declension grammar information:
```bash
$ duden Barmherzigkeit --grammar
singular nominativ | die Barmherzigkeit 
genitiv  singular  | der Barmherzigkeit 
singular dativ     | der Barmherzigkeit 
singular akkusativ | die Barmherzigkeit

$ duden laufen --grammar plural,präsens
indikativ    person i     | wir laufen 
konjunktiv i person i     | wir laufen 
imperativ    person i     | –          
person ii    indikativ    | ihr lauft  
person ii    konjunktiv i | ihr laufet 
person ii    imperativ    | lauft!     
indikativ    person iii   | sie laufen 
konjunktiv i person iii   | sie laufen 
person iii   imperativ    | –
```

By the way with this short code you should be able to extract the text from the grammar section for prepositions too:

```python
import duden
word = duden.get('auf_Praeposition')  # using urlname for 'auf'
grammar_section = word.soup.find('div', id='grammatik')
grammar_section.header.extract()  # get rid of the "Grammatik (Info)" header

print(grammar_section.text.strip())
```

If you feel like this feature is missing in the module, feel free to create a feature request via an issue.
